id = "zen-abyssal"
name = "Zen Abyssal"
schema_version = 1
version = "0.1.0"
authors = ["KevInCompile <kevcoc10@gmail.com>"]
description = "A theme you'll probably like for zed."
repository = "https://github.com/KevInCompile/ZenAbyssal"
